version: '3'
services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 11510:3306
    networks:
      - dev-network
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - dev-mariadb:/var/lib/mariadb

volumes:
  dev-mariadb:

networks:
  dev-network:
    driver: bridge